### ISSUE TITLE
Update HtmlAgilityPack.NetCore to Official HtmlAgilityPack 1.6.15 (supports .net core)

### ISSUE THREAD

**Issue by dotnetshadow** [trenoncourt/HtmlAgilityPack.CssSelectors.NetCore#5]
Hi there,

I noticed that you are referencing **HtmlAgilityPack.NetCore**

**HtmlAgility** now supports .net core I think so could be worth upgrading to it?

Also maybe you can target it so that if you have HtmlAgilityPack installed that it can use that?

**Comment by dotnetshadow** [comment]
Thank you 👍

**Comment by trenoncourt** [comment]
You're welcome :blush:
